name: Automating Create Pull Request

on:
  push:

jobs:
  auto-pull-request:
    name: Create Action
    runs-on: ubuntu-latest

    if: endsWith(github.event.head_commit.message, 'pr')
    steps:
      - uses: actions/checkout@v2

      - name: Create Hotfix PR Action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "hotfix/"
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_TITLE: ${{ format('[HOTFIX] {0}', github.ref_name) }}
          
      - name: Create Feature PR Action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "feature/"
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_TITLE: ${{ format('[FEATURE] by {0}', github.actor) }}
          PULL_REQUEST_BODY: "Î≥ÄÍ≤Ω ÏÇ¨Ìï≠ÏùÑ Í∏∞Î°ùÌï¥ Ï£ºÏÑ∏Ïöîüë£"
          
      - name: Create Bugfix PR Action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "bugfix/"
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_TITLE: ${{ format('[BUGFIX] by {0}', github.actor) }}      
          PULL_REQUEST_BODY: "ÏàòÏ†ï ÏÇ¨Ìï≠ÏùÑ Í∏∞Î°ùÌï¥ Ï£ºÏÑ∏Ïöîüòé"
      
      - name: Create Refactor PR Action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "refactor/"
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_TITLE: ${{ format('[REFACTOR] by {0}', github.actor) }}
          PULL_REQUEST_BODY: "Î¶¨Ìå©ÌÜ†ÎßÅ ÎÇ¥Ïö©ÏùÑ Í∏∞Î°ùÌï¥ Ï£ºÏÑ∏ÏöîüëÄ"
          
          
          
